"""
GEX TradingView Pusher
Calculates GEX from Dhan API and pushes Pine Script indicator to TradingView
via TradingView MCP. Run every 5 minutes for near-live levels.

Usage:
  python gex_tv_push.py           (both NIFTY + BANKNIFTY)
  python gex_tv_push.py NIFTY     (NIFTY only)
  python gex_tv_push.py --loop    (auto-refresh every 5 min)
"""

import sys
import time
import json
import subprocess
from datetime import datetime
from gex_calculator import run_gex, UNDERLYINGS


def generate_combined_pine(nifty_data=None, bnf_data=None):
    """Generate Pine Script with both NIFTY + BANKNIFTY GEX levels, toggles, and text boxes."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    def fmt(n):
        abs_n = abs(n)
        if abs_n >= 1e9:
            return f"{n/1e9:.1f}B"
        elif abs_n >= 1e6:
            return f"{n/1e6:.1f}M"
        elif abs_n >= 1e3:
            return f"{n/1e3:.1f}K"
        return f"{n:.0f}"

    def extract(data):
        if not data:
            return None
        levels = data["levels"]
        local_flip = levels.get("local_flip", {})
        return {
            "symbol": data["symbol"],
            "spot": data["spot"],
            "expiry": data["expiry"],
            "call_wall": levels.get("call_wall", 0),
            "put_wall": levels.get("put_wall", 0),
            "hvl": levels.get("hvl", 0),
            "local_flip_strike": local_flip.get("strike", 0) if local_flip else 0,
            "gamma_cond": levels.get("gamma_condition", "UNKNOWN"),
            "gamma_tilt": levels.get("gamma_tilt", 0),
            "net_gex": data["net_gex"],
            "call_gex": data["call_gex"],
            "put_gex": data["put_gex"],
            "pc_ratio": f"{abs(data['put_gex']/data['call_gex']):.2f}" if data['call_gex'] != 0 else "N/A",
            "peak_gamma": levels.get("peak_gamma", 0),
            "max_pain": levels.get("max_pain", 0),
            "bias": levels.get("bias", "NEUTRAL"),
            "bias_score": levels.get("bias_score", 0),
            "top_nearby": get_top_nearby(data),
            # Expected Move (daily 1SD)
            "em_upper": levels.get("em_upper", 0) or 0,
            "em_lower": levels.get("em_lower", 0) or 0,
            "em_wk_upper": levels.get("em_wk_upper", 0) or 0,
            "em_wk_lower": levels.get("em_wk_lower", 0) or 0,
            "atm_iv": levels.get("atm_iv", 0),
            "dte": levels.get("dte", 0),
            # IV Skew
            "iv_skew": levels.get("iv_skew", 0),
            "skew_signal": levels.get("skew_signal", "NEUTRAL"),
            # OI Change
            "oi_buildups": levels.get("oi_buildups", []),
            "total_ce_oi_chg": levels.get("total_ce_oi_chg", 0),
            "total_pe_oi_chg": levels.get("total_pe_oi_chg", 0),
            "net_oi_chg_direction": levels.get("net_oi_chg_direction", "N/A"),
            "has_prev_data": levels.get("has_prev_data", False),
            # Regime
            "regime": levels.get("regime", "MIXED"),
            "regime_score": levels.get("regime_score", 0),
        }

    def get_top_nearby(data):
        spot = data["spot"]
        strikes_data = data.get("strikes", [])
        nearby = [r for r in strikes_data if abs(r["strike"] - spot) < spot * 0.03]
        return sorted(nearby, key=lambda x: abs(x["net_gex"]), reverse=True)[:5]

    n = extract(nifty_data)
    b = extract(bnf_data)

    # Define level configs: (key, default_color_hex, default_width, default_style, label_prefix)
    level_defs = [
        ("CW", "Call Wall", "#FF0000", 3, "Solid"),
        ("PW", "Put Wall", "#00FF00", 3, "Solid"),
        ("HVL", "HVL", "#FF9800", 3, "Dashed"),
        ("FLIP", "Local Flip", "#FFEB3B", 2, "Dotted"),
        ("PG", "Peak Gamma", "#FF00FF", 3, "Solid"),
        ("MP", "Max Pain", "#00FFFF", 3, "Dashed"),
    ]

    pine = f'''// This file is auto-generated by gex_tv_push.py
// Last updated: {timestamp}
//@version=6
indicator("GEX Levels", overlay=true, max_lines_count=500, max_labels_count=500)

// ===== DISPLAY TOGGLES =====
showNifty = input.bool(true, "Show NIFTY", group="Display")
showBNF = input.bool(true, "Show BANKNIFTY", group="Display")
showTable = input.bool(true, "Show Levels Table", group="Display")
showTopStrikes = input.bool(true, "Top GEX Strikes", group="Display")
showEM = input.bool(true, "Expected Move Zone", group="Display")
showOI = input.bool(true, "OI Buildup Lines", group="Display")

// ===== LEVEL STYLE INPUTS =====
'''

    # Generate style inputs for each level type
    for key, name, def_color, def_width, def_style in level_defs:
        pine += f'show{key} = input.bool(true, "{name}", group="{name} Style")\n'
        pine += f'clr{key} = input.color({def_color}, "Color", group="{name} Style")\n'
        pine += f'wid{key} = input.int({def_width}, "Width", minval=1, maxval=5, group="{name} Style")\n'
        pine += f'sty{key}Str = input.string("{def_style}", "Style", options=["Solid", "Dashed", "Dotted"], group="{name} Style")\n'

    pine += '''clrEM = input.color(#2196F3, "Color", group="Expected Move Style")
widEM = input.int(2, "Width", minval=1, maxval=5, group="Expected Move Style")
styEMStr = input.string("Dashed", "Style", options=["Solid", "Dashed", "Dotted"], group="Expected Move Style")

// Style string to line.style converter
lineStyle(string s) =>
    s == "Dashed" ? line.style_dashed : s == "Dotted" ? line.style_dotted : line.style_solid

'''

    pine += f'var string UPDATED = "{timestamp}"\n'

    # NIFTY levels
    if n:
        pine += f'''
// ===== NIFTY LEVELS (editable) =====
N_CW = input.float({n["call_wall"]:.0f}, "Call Wall", group="NIFTY Levels")
N_PW = input.float({n["put_wall"]:.0f}, "Put Wall", group="NIFTY Levels")
N_HVL = input.float({n["hvl"]:.2f}, "HVL", group="NIFTY Levels")
N_FLIP = input.float({n["local_flip_strike"]:.2f}, "Local Flip", group="NIFTY Levels")
N_PG = input.float({n["peak_gamma"]:.0f}, "Peak Gamma", group="NIFTY Levels")
N_MP = input.float({n["max_pain"]:.0f}, "Max Pain", group="NIFTY Levels")
var string N_GAMMA_COND = "{n["gamma_cond"]}"
var float N_GAMMA_TILT = {n["gamma_tilt"]:.1f}
var float N_NET_GEX = {n["net_gex"]:.0f}
var string N_EXPIRY = "{n["expiry"]}"
var string N_BIAS = "{n["bias"]}"
var int N_BIAS_SCORE = {n["bias_score"]}
var float N_EM_UP = {n["em_upper"]:.2f}
var float N_EM_LO = {n["em_lower"]:.2f}
var float N_EM_WK_UP = {n["em_wk_upper"]:.2f}
var float N_EM_WK_LO = {n["em_wk_lower"]:.2f}
var float N_ATM_IV = {n["atm_iv"]:.1f}
var int N_DTE = {n["dte"]}
var float N_IV_SKEW = {n["iv_skew"]:.2f}
var string N_SKEW_SIG = "{n["skew_signal"]}"
var string N_OI_DIR = "{n["net_oi_chg_direction"]}"
var int N_OI_CE_CHG = {n["total_ce_oi_chg"]}
var int N_OI_PE_CHG = {n["total_pe_oi_chg"]}
var bool N_HAS_OI = {"true" if n["has_prev_data"] else "false"}
var string N_REGIME = "{n["regime"]}"
var int N_REGIME_SCORE = {n["regime_score"]}
'''

    if b:
        pine += f'''
// ===== BANKNIFTY LEVELS (editable) =====
B_CW = input.float({b["call_wall"]:.0f}, "Call Wall", group="BANKNIFTY Levels")
B_PW = input.float({b["put_wall"]:.0f}, "Put Wall", group="BANKNIFTY Levels")
B_HVL = input.float({b["hvl"]:.2f}, "HVL", group="BANKNIFTY Levels")
B_FLIP = input.float({b["local_flip_strike"]:.2f}, "Local Flip", group="BANKNIFTY Levels")
B_PG = input.float({b["peak_gamma"]:.0f}, "Peak Gamma", group="BANKNIFTY Levels")
B_MP = input.float({b["max_pain"]:.0f}, "Max Pain", group="BANKNIFTY Levels")
var string B_GAMMA_COND = "{b["gamma_cond"]}"
var float B_GAMMA_TILT = {b["gamma_tilt"]:.1f}
var float B_NET_GEX = {b["net_gex"]:.0f}
var string B_EXPIRY = "{b["expiry"]}"
var string B_BIAS = "{b["bias"]}"
var int B_BIAS_SCORE = {b["bias_score"]}
var float B_EM_UP = {b["em_upper"]:.2f}
var float B_EM_LO = {b["em_lower"]:.2f}
var float B_EM_WK_UP = {b["em_wk_upper"]:.2f}
var float B_EM_WK_LO = {b["em_wk_lower"]:.2f}
var float B_ATM_IV = {b["atm_iv"]:.1f}
var int B_DTE = {b["dte"]}
var float B_IV_SKEW = {b["iv_skew"]:.2f}
var string B_SKEW_SIG = "{b["skew_signal"]}"
var string B_OI_DIR = "{b["net_oi_chg_direction"]}"
var int B_OI_CE_CHG = {b["total_ce_oi_chg"]}
var int B_OI_PE_CHG = {b["total_pe_oi_chg"]}
var bool B_HAS_OI = {"true" if b["has_prev_data"] else "false"}
var string B_REGIME = "{b["regime"]}"
var int B_REGIME_SCORE = {b["regime_score"]}
'''

    # Session detection + line drawing using hline-like approach with session bars
    # We track session start bar and draw persistent lines across the session
    pine += '''
// ===== SESSION TRACKING =====
var int sessStart = na
newSess = session.isfirstbar
if newSess
    sessStart := bar_index

// Helper: draw a session-wide level line + label on last bar
drawLevel(float price, color clr, int wid, string styStr, string txt, bool show) =>
    if show and not na(price) and price > 0 and barstate.islast
        startBar = na(sessStart) ? bar_index - 50 : sessStart
        l = line.new(startBar, price, bar_index + 15, price, color=clr, width=wid, style=lineStyle(styStr), extend=extend.none)
        label.new(bar_index + 17, price, txt, style=label.style_label_left, color=clr, textcolor=color.white, size=size.small)

// ===== DRAW LEVELS =====
'''

    if n:
        pine += '''// --- NIFTY ---
if showNifty
    drawLevel(N_CW, clrCW, widCW, styCWStr, "Call Wall " + str.tostring(N_CW, "#"), showCW)
    drawLevel(N_PW, clrPW, widPW, styPWStr, "Put Wall " + str.tostring(N_PW, "#"), showPW)
    drawLevel(N_HVL, clrHVL, widHVL, styHVLStr, "HVL " + str.tostring(N_HVL, "#.##"), showHVL)
    drawLevel(N_FLIP, clrFLIP, widFLIP, styFLIPStr, "Local Flip " + str.tostring(N_FLIP, "#.##"), showFLIP)
    drawLevel(N_PG, clrPG, widPG, styPGStr, "Peak Gamma " + str.tostring(N_PG, "#"), showPG)
    drawLevel(N_MP, clrMP, widMP, styMPStr, "Max Pain " + str.tostring(N_MP, "#"), showMP)
'''

        # Top strikes for NIFTY
        pine += '    if showTopStrikes and barstate.islast\n'
        pine += '        int sBar = na(sessStart) ? bar_index - 50 : sessStart\n'
        for i, s in enumerate(n["top_nearby"]):
            gex_str = fmt(s["net_gex"])
            pine += f'        line.new(sBar, {s["strike"]:.2f}, bar_index + 10, {s["strike"]:.2f}, color=color.new(color.blue, 40), width=1, style=line.style_dotted)\n'
            pine += f'        label.new(sBar - 2, {s["strike"]:.2f}, "{s["strike"]:.0f} ({gex_str})", style=label.style_label_right, color=color.new(color.gray, 70), textcolor=color.white, size=size.small)\n'

        # EM band for NIFTY
        pine += '''    if showEM and barstate.islast and N_EM_UP > 0 and N_EM_LO > 0
        int emBar = na(sessStart) ? bar_index - 50 : sessStart
        // Weekly EM (outer, lighter zone)
        emWkUp = line.new(emBar, N_EM_WK_UP, bar_index + 15, N_EM_WK_UP, color=color.new(clrEM, 50), width=1, style=line.style_dotted)
        emWkLo = line.new(emBar, N_EM_WK_LO, bar_index + 15, N_EM_WK_LO, color=color.new(clrEM, 50), width=1, style=line.style_dotted)
        linefill.new(emWkUp, emWkLo, color=color.new(clrEM, 93))
        // Daily EM (inner, solid zone)
        emUpLine = line.new(emBar, N_EM_UP, bar_index + 15, N_EM_UP, color=clrEM, width=widEM, style=lineStyle(styEMStr))
        emLoLine = line.new(emBar, N_EM_LO, bar_index + 15, N_EM_LO, color=clrEM, width=widEM, style=lineStyle(styEMStr))
        linefill.new(emUpLine, emLoLine, color=color.new(clrEM, 85))
        label.new(bar_index + 17, N_EM_UP, "EM+ " + str.tostring(N_EM_UP, "#"), style=label.style_label_left, color=clrEM, textcolor=color.white, size=size.small)
        label.new(bar_index + 17, N_EM_LO, "EM- " + str.tostring(N_EM_LO, "#"), style=label.style_label_left, color=clrEM, textcolor=color.white, size=size.small)
'''

        # OI buildup lines for NIFTY
        if n["has_prev_data"] and n["oi_buildups"]:
            pine += '    if showOI and barstate.islast\n'
            pine += '        int oiBar = na(sessStart) ? bar_index - 50 : sessStart\n'
            for bu in n["oi_buildups"]:
                chg_str = fmt(bu["net_oi_chg"])
                pine += f'        line.new(oiBar, {bu["strike"]:.2f}, bar_index + 10, {bu["strike"]:.2f}, color=color.new(#4CAF50, 30), width=2, style=line.style_dashed)\n'
                pine += f'        label.new(oiBar - 2, {bu["strike"]:.2f}, "OI+ {bu["strike"]:.0f} (+{chg_str})", style=label.style_label_right, color=color.new(#4CAF50, 50), textcolor=color.white, size=size.small)\n'

    if b:
        pine += '''
// --- BANKNIFTY ---
if showBNF
    drawLevel(B_CW, color.new(clrCW, 30), widCW, styCWStr, "BN Call Wall " + str.tostring(B_CW, "#"), showCW)
    drawLevel(B_PW, color.new(clrPW, 30), widPW, styPWStr, "BN Put Wall " + str.tostring(B_PW, "#"), showPW)
    drawLevel(B_HVL, color.new(clrHVL, 30), widHVL, styHVLStr, "BN HVL " + str.tostring(B_HVL, "#.##"), showHVL)
    drawLevel(B_FLIP, color.new(clrFLIP, 30), widFLIP, styFLIPStr, "BN Local Flip " + str.tostring(B_FLIP, "#.##"), showFLIP)
    drawLevel(B_PG, color.new(clrPG, 30), widPG, styPGStr, "BN Peak Gamma " + str.tostring(B_PG, "#"), showPG)
    drawLevel(B_MP, color.new(clrMP, 30), widMP, styMPStr, "BN Max Pain " + str.tostring(B_MP, "#"), showMP)
'''

        pine += '    if showTopStrikes and barstate.islast\n'
        pine += '        int sBar2 = na(sessStart) ? bar_index - 50 : sessStart\n'
        for i, s in enumerate(b["top_nearby"]):
            gex_str = fmt(s["net_gex"])
            pine += f'        line.new(sBar2, {s["strike"]:.2f}, bar_index + 10, {s["strike"]:.2f}, color=color.new(color.purple, 40), width=1, style=line.style_dotted)\n'
            pine += f'        label.new(sBar2 - 2, {s["strike"]:.2f}, "BN {s["strike"]:.0f} ({gex_str})", style=label.style_label_right, color=color.new(color.gray, 70), textcolor=color.white, size=size.small)\n'

        # EM band for BANKNIFTY
        pine += '''    if showEM and barstate.islast and B_EM_UP > 0 and B_EM_LO > 0
        int emBar2 = na(sessStart) ? bar_index - 50 : sessStart
        // Weekly EM (outer, lighter zone)
        emWkUp2 = line.new(emBar2, B_EM_WK_UP, bar_index + 15, B_EM_WK_UP, color=color.new(clrEM, 60), width=1, style=line.style_dotted)
        emWkLo2 = line.new(emBar2, B_EM_WK_LO, bar_index + 15, B_EM_WK_LO, color=color.new(clrEM, 60), width=1, style=line.style_dotted)
        linefill.new(emWkUp2, emWkLo2, color=color.new(clrEM, 95))
        // Daily EM (inner, solid zone)
        emUpLine2 = line.new(emBar2, B_EM_UP, bar_index + 15, B_EM_UP, color=color.new(clrEM, 30), width=widEM, style=lineStyle(styEMStr))
        emLoLine2 = line.new(emBar2, B_EM_LO, bar_index + 15, B_EM_LO, color=color.new(clrEM, 30), width=widEM, style=lineStyle(styEMStr))
        linefill.new(emUpLine2, emLoLine2, color=color.new(clrEM, 90))
        label.new(bar_index + 17, B_EM_UP, "BN EM+ " + str.tostring(B_EM_UP, "#"), style=label.style_label_left, color=color.new(clrEM, 30), textcolor=color.white, size=size.small)
        label.new(bar_index + 17, B_EM_LO, "BN EM- " + str.tostring(B_EM_LO, "#"), style=label.style_label_left, color=color.new(clrEM, 30), textcolor=color.white, size=size.small)
'''

        # OI buildup lines for BANKNIFTY
        if b["has_prev_data"] and b["oi_buildups"]:
            pine += '    if showOI and barstate.islast\n'
            pine += '        int oiBar2 = na(sessStart) ? bar_index - 50 : sessStart\n'
            for bu in b["oi_buildups"]:
                chg_str = fmt(bu["net_oi_chg"])
                pine += f'        line.new(oiBar2, {bu["strike"]:.2f}, bar_index + 10, {bu["strike"]:.2f}, color=color.new(#4CAF50, 30), width=2, style=line.style_dashed)\n'
                pine += f'        label.new(oiBar2 - 2, {bu["strike"]:.2f}, "BN OI+ {bu["strike"]:.0f} (+{chg_str})", style=label.style_label_right, color=color.new(#4CAF50, 50), textcolor=color.white, size=size.small)\n'

    # Table
    n_rows = 2
    if n:
        n_rows += 16  # 15 + regime row
    if b:
        n_rows += 16  # 15 + regime row

    pine += f'''
// ===== LEVELS TEXT BOX =====
var table lvlBox = table.new(position.top_right, 2, {n_rows}, bgcolor=color.new(color.black, 10), border_width=1, border_color=color.new(color.gray, 50))

if barstate.islast and showTable
    int row = 0
    table.cell(lvlBox, 0, row, "GEX LEVELS", text_color=color.white, text_size=size.normal, bgcolor=color.new(color.blue, 30))
    table.cell(lvlBox, 1, row, UPDATED, text_color=color.gray, text_size=size.small, bgcolor=color.new(color.blue, 30))
    row += 1
'''

    if n:
        pine += f'''
    if showNifty
        table.cell(lvlBox, 0, row, "NIFTY", text_color=color.white, text_size=size.normal, bgcolor=color.new(color.teal, 40))
        nBClr = N_BIAS == "STRONG BULL" or N_BIAS == "BULL" ? color.green : N_BIAS == "NEUTRAL" ? color.orange : color.red
        table.cell(lvlBox, 1, row, N_BIAS + " (" + str.tostring(N_BIAS_SCORE) + "/7)", text_color=nBClr, text_size=size.normal, bgcolor=color.new(color.teal, 40))
        row += 1
        nGClr = N_GAMMA_COND == "POSITIVE" ? color.green : color.red
        table.cell(lvlBox, 0, row, "Gamma", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, N_GAMMA_COND + " | " + str.tostring(N_GAMMA_TILT, "#.#") + "% Bull", text_color=nGClr, text_size=size.small)
        row += 1
        table.cell(lvlBox, 0, row, "Call Wall", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_CW, "#"), text_color=clrCW, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Put Wall", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_PW, "#"), text_color=clrPW, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "HVL", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_HVL, "#.##"), text_color=clrHVL, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Local Flip", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_FLIP, "#.##"), text_color=clrFLIP, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Peak Gamma", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_PG, "#"), text_color=clrPG, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Max Pain", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_MP, "#"), text_color=clrMP, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Net GEX", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, "{fmt(n["net_gex"])}", text_color=N_NET_GEX > 0 ? color.green : color.red, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Expiry", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, N_EXPIRY, text_color=color.white, text_size=size.small)
        row += 1
        table.cell(lvlBox, 0, row, "P/C GEX", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, "{n["pc_ratio"]}", text_color=color.white, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Exp Move", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_EM_LO, "#") + " - " + str.tostring(N_EM_UP, "#"), text_color=clrEM, text_size=size.normal)
        row += 1
        nSkClr = N_IV_SKEW > 1 ? color.red : N_IV_SKEW < -1 ? color.green : color.orange
        table.cell(lvlBox, 0, row, "IV Skew", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(N_IV_SKEW, "#.##") + " " + N_SKEW_SIG, text_color=nSkClr, text_size=size.small)
        row += 1
        table.cell(lvlBox, 0, row, "OI Chg", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, N_HAS_OI ? N_OI_DIR : "No prev data", text_color=N_OI_DIR == "BUILDUP" ? color.green : color.red, text_size=size.small)
        row += 1
        nRClr = N_REGIME == "RANGE" ? color.blue : N_REGIME == "TREND" ? color.orange : color.gray
        nRText = N_REGIME == "RANGE" ? N_REGIME + " " + str.tostring(N_PW, "#") + "-" + str.tostring(N_CW, "#") : N_REGIME == "TREND" ? N_REGIME + " (follow momentum)" : N_REGIME
        table.cell(lvlBox, 0, row, "Regime", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, nRText, text_color=nRClr, text_size=size.normal)
        row += 1
'''

    if b:
        pine += f'''
    if showBNF
        table.cell(lvlBox, 0, row, "BANKNIFTY", text_color=color.white, text_size=size.normal, bgcolor=color.new(color.purple, 40))
        bBClr = B_BIAS == "STRONG BULL" or B_BIAS == "BULL" ? color.green : B_BIAS == "NEUTRAL" ? color.orange : color.red
        table.cell(lvlBox, 1, row, B_BIAS + " (" + str.tostring(B_BIAS_SCORE) + "/7)", text_color=bBClr, text_size=size.normal, bgcolor=color.new(color.purple, 40))
        row += 1
        bGClr = B_GAMMA_COND == "POSITIVE" ? color.green : color.red
        table.cell(lvlBox, 0, row, "Gamma", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, B_GAMMA_COND + " | " + str.tostring(B_GAMMA_TILT, "#.#") + "% Bull", text_color=bGClr, text_size=size.small)
        row += 1
        table.cell(lvlBox, 0, row, "Call Wall", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_CW, "#"), text_color=clrCW, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Put Wall", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_PW, "#"), text_color=clrPW, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "HVL", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_HVL, "#.##"), text_color=clrHVL, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Local Flip", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_FLIP, "#.##"), text_color=clrFLIP, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Peak Gamma", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_PG, "#"), text_color=clrPG, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Max Pain", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_MP, "#"), text_color=clrMP, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Net GEX", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, "{fmt(b["net_gex"])}", text_color=B_NET_GEX > 0 ? color.green : color.red, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Expiry", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, B_EXPIRY, text_color=color.white, text_size=size.small)
        row += 1
        table.cell(lvlBox, 0, row, "P/C GEX", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, "{b["pc_ratio"]}", text_color=color.white, text_size=size.normal)
        row += 1
        table.cell(lvlBox, 0, row, "Exp Move", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_EM_LO, "#") + " - " + str.tostring(B_EM_UP, "#"), text_color=clrEM, text_size=size.normal)
        row += 1
        bSkClr = B_IV_SKEW > 1 ? color.red : B_IV_SKEW < -1 ? color.green : color.orange
        table.cell(lvlBox, 0, row, "IV Skew", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, str.tostring(B_IV_SKEW, "#.##") + " " + B_SKEW_SIG, text_color=bSkClr, text_size=size.small)
        row += 1
        table.cell(lvlBox, 0, row, "OI Chg", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, B_HAS_OI ? B_OI_DIR : "No prev data", text_color=B_OI_DIR == "BUILDUP" ? color.green : color.red, text_size=size.small)
        row += 1
        bRClr = B_REGIME == "RANGE" ? color.blue : B_REGIME == "TREND" ? color.orange : color.gray
        bRText = B_REGIME == "RANGE" ? B_REGIME + " " + str.tostring(B_PW, "#") + "-" + str.tostring(B_CW, "#") : B_REGIME == "TREND" ? B_REGIME + " (follow momentum)" : B_REGIME
        table.cell(lvlBox, 0, row, "Regime", text_color=color.gray, text_size=size.small)
        table.cell(lvlBox, 1, row, bRText, text_color=bRClr, text_size=size.normal)
        row += 1
'''

    return pine


def push_to_tradingview(pine_code, symbol="combined"):
    """Save Pine Script to file."""
    filename = f"C:/tv/gex_{symbol.lower()}_indicator.pine"
    with open(filename, "w") as f:
        f.write(pine_code)
    print(f"Pine Script saved to {filename}")
    return pine_code


def main():
    loop_mode = "--loop" in sys.argv
    # If specific symbol given, only fetch that one
    args = [a.upper() for a in sys.argv[1:] if not a.startswith("--")]

    while True:
        print(f"\n{'='*50}")
        print(f"  GEX Update - {datetime.now().strftime('%H:%M:%S')}")
        print(f"{'='*50}")

        nifty_data = None
        bnf_data = None

        if not args or "NIFTY" in args:
            nifty_data = run_gex("NIFTY")

        if not args or "BANKNIFTY" in args:
            import time as t
            if nifty_data:
                t.sleep(2)  # Rate limit between API calls
            bnf_data = run_gex("BANKNIFTY")

        if nifty_data or bnf_data:
            pine_code = generate_combined_pine(nifty_data, bnf_data)
            if pine_code:
                push_to_tradingview(pine_code, "combined")
                # Also save individual files for reference
                if nifty_data:
                    push_to_tradingview(
                        generate_combined_pine(nifty_data, None), "nifty"
                    )
                if bnf_data:
                    push_to_tradingview(
                        generate_combined_pine(None, bnf_data), "banknifty"
                    )
                print(f"\n[OK] Pine Script ready")
                print(f"     Use TradingView MCP pine_set_source to push it")
            else:
                print("[ERROR] Failed to generate Pine Script")
        else:
            print("[ERROR] Failed to calculate GEX")

        if not loop_mode:
            break

        print(f"\nNext update in 5 minutes...")
        time.sleep(300)


if __name__ == "__main__":
    main()
